version: 2

sources:
  - name: stg
    schema: sk_stg
    tables:
    - name: cust
      identifier: customer
    - name: address
    - name: city
    - name: country
    - name: film
    - name: film_cat
      identifier: film_category
    - name: cat
      identifier: category
    - name: lang
      identifier: language
    - name: inventory
      identifier: inventory
    - name: rental
    - name: payment
    - name: staff
    - name: store
    - name: z_refresh_from